# Generated by Django 2.2.10 on 2021-06-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210603_1732'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupchat',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='group_chat_name_owner_unique'),
        ),
    ]
